Milestone 4
kazumaki/react-calculator pull request #4
Opened 2020-05-30 18:17 UTC by kazumaki

Create the logic modules for the calculator

2020-05-30 21:49 UTC, bolah2009 requested changes
Hi @kazumaki 

Good job with the project.

Can you please merge #1, #2 and #3, then make sure there are no conflicts before continuing with this milestone?
Also, I noticed you have open another PR #5 for Milestone 5. Please, don't do this as the project is in milestones for a reason.

### Please see the comment below for the required changes.

#### :recycle:  Make these changes and submit another code review request. 👍🏾

#### Feel free to reach me on slack if you having issues implementing these features. :relaxed: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2020-05-30 21:49 UTC, bolah2009 commented on src/logic/calculate.js
> +};
This logic is not comprehensive enough.

Think of cases you need to handle, please remember that `calculate` is the only place where the app logic would be. For each click, `calculate` function will be called.

Think of this and make changes accordingly.

2020-06-01 05:37 UTC, fatymahmed requested changes
Hi @kazumaki,

As mentioned in the previous review, `calculate` will be called for each button click, that means you should cover all cases.

See my comment below
### Please make the required change then request for another review ♻️
_Feel free to reach out to me on slack (Fatima) if you have any questions_

2020-06-01 05:41 UTC, fatymahmed commented on src/logic/calculate.js
> +    returnData.display = returnData.next;
- You are only covering cases for `+` `-` `x`  `%` `/` `=` `+/-`, what about when the user clicks on `AC` or `.` or when an operation is done with `0` (like division or multiplication)?

2020-06-01 12:10 UTC, Oghenebrume50 approved these changes
### STATUS: CHANGES REQUIRED

Hi @kazumaki good job working on this,  you have met all the corrections as outlined by the previous reviewers, please merge and move on to the next milestone :+1: 

**RAPHAEL NORIODE** :mask:

2020-06-10 23:20 UTC, merged