Milestone 5
kazumaki/react-calculator pull request #5
Opened 2020-05-30 21:41 UTC by kazumaki

Connect calculate and operate modules to app component to show the results.

2020-06-02 10:47 UTC, shloch requested changes
## Hello @kazumaki , 

Great job...everything works fine
You however have one small bug to rectify (mentioned below) and we'll be good

### Happy coding

2020-06-02 10:47 UTC, shloch commented on src/components/App.js
> +
### [Optional]
You can center calculator to be in middle of screen
```
    margin: auto;
```

2020-06-02 10:47 UTC, shloch commented on src/logic/operate.js
> +    result = bigOne.div(bigTwo);
### [Required]
You've not managed division by ZERO...please handle this
![calc](https://user-images.githubusercontent.com/40712459/83511459-947e3380-a4c6-11ea-828c-7c540e127c5e.gif)

2020-06-02 10:50 UTC, shloch commented on src/logic/operate.js
> +    result = bigOne.div(bigTwo);
As you can see from gif, in beginning, normal division wasn;t working, i dont know why....then i refreshed, works fine...except for DIVISION BY  ZERO

Also please try to increase the font size of buttons a little.....looks smaller and you got space, thanks

2020-06-03 06:48 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED

Hi @kazumaki good job starting this and also working with the previous reviewer to fix the bug he pointed out :+1: but it seems there are more breaking changes now :slightly_smiling_face:  I will add a video link [here](https://www.loom.com/share/76d7e6763da04b0489b01addc756c530) please look at it 

Also, the division by zero error is not corrected either this shows in the video too 
Using the previous answer to make a further calculation is not well supported, for example, type 8 * 3 would give 24, if the user then types + 6 it should give 30 but the answer remains 6. 
This and some other issues are shown in the video linked here 

Please make changes and request for another review :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask:

2020-06-04 06:19 UTC, bellom approved these changes
## Hi @kazumaki  :clap: 

**Great work making all the necessary corrections from the previous review.**

NOTE: It would be better to return a message on the screen whenever users divide with zero just like a normal calculator, in your case you return `0`

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-06-10 23:22 UTC, merged